### ISSUE TITLE
No file found: debug/samples.pkl

### ISSUE THREAD

**Issue by HONGJINLYU** [pmh9960/iColoriT#8]
when I try to run the train.sh. I got the following error:

 Traceback (most recent call last):
  File "train.py", line 276, in <module>
    main(args)
  File "train.py", line 146, in main
    dataset_train = build_pretraining_dataset(args)
  File "/home/PycharmProjects/Year_2021/iColoriT-main/datasets.py", line 171, in build_pretraining_dataset
    return ImageFolder(args.data_path, transform=transform)
  File "/home/PycharmProjects/Year_2021/iColoriT-main/dataset_folder.py", line 248, in __init__
    super(ImageFolder, self).__init__(root, loader, IMG_EXTENSIONS if is_valid_file is None else None,
  File "/home/PycharmProjects/Year_2021/iColoriT-main/dataset_folder.py", line 123, in __init__
    with open('debug/samples.pkl', 'rb') as f:

Could you tell me what is the meaning and function of this debug/samples.pkl?
For my own training dataset,how to create the corresponding samples.pkl?
Many thanks for your kind help!

**Comment by pmh9960** [comment]
Hi, thanks you for your interest in our work, and thank you for your comment. 

The point you mentioned was regarding the function in which `DatasetFolder` initially explores all the files, and we were caching it manually. We realized that this approach was incorrect when sharing the code. Therefore, we have made the following modification accordingly.

https://github.com/pmh9960/iColoriT/blob/8a02415aea6f6cc144650b47f38e58476f4e2a0f/dataset_folder.py#L121-L124

Any PRs are welcome!
Best,
